---
- name: Install Apache WebServer
  hosts: localhost

  tasks: 
    - name: Install Apache on Ubuntu Server
      apt: 
        name: apache2
        state: present
      when: ansible_os_family == "Ubuntu"

    - name: Install Apache on CentOS Server
      dnf:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat" 
